### ISSUE TITLE
In Windows 10 latest failed clicks produced

### ISSUE THREAD

**Issue by Galaxy-Wizard** [desowin/usbpcap#70] opened 2019-02-05 23:09 UTC
After installation on Windows 10 latest failed clicks produced.
For example:
1) i press left mouse button
there may appear two reactions:
1) generated 2 left mouse presses (double click)
2) generated 2 clicks: first is right mouse click and second is left click.

Something similar is when i press right mouse button.
But i do not know exactly, what presses are generated by driver.
I suppose the same situation.

I general, i as suppose, when any mouse button is pressed, then random (left or right button) click is produced and the real button click is produced.

I got you fault program with Wires Shark latest.

I deleted your program some times, but it return and installs itself in my computer with Windows 10.
I have deleted your fault program.

As i am being software developer, i gave you my tests of your fault program.

**Comment by desowin** [comment] 2019-03-31 11:12
USBPcap does not affect the transferred data at all, it only snoops the USB IRPs and logs them to the capture buffer (if capture is ongoing). I have no idea how the problem you are reporting could be connected to the USBPcapDriver. For me it looks like the issue is with the mouse hardware itself.

I have never experienced such issue myself nor any of the people using USBPcap has observed such strange issue. If someone observes such issue and is certain that it is not the actual HW sending the phantom clicks, please comment here.

**Closed by desowin** 2019-03-31 11:12 UTC
